name: Deploy on Comment

on:
  issue_comment:
    types: [created]

jobs:
  deploy:
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/get_pr_html_url')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Pull Request URL
        id: get-pr-url
        run: |
          PR_URL_OUT_PUT=$(jq --raw-output .issue.pull_request.html_url "$GITHUB_EVENT_PATH")
          echo "PR_URL=$PR_URL_OUT_PUT"　>> $GITHUB_ENV

      - name: Use Pull Request URL
        run: |
          echo "Using Pull Request URL: ${PR_URL}"
